services:
  # InfluxDB - Time series database for counter data (Performance Optimized)
  influxdb:
    image: influxdb:2.7.12
    container_name: adam-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=adam_org
      - DOCKER_INFLUXDB_INIT_BUCKET=adam_counters
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=adam-super-secret-token
      # Performance optimization settings
      - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=1g
      - INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE=25m
      - INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION=10m
      - INFLUXD_STORAGE_WAL_FSYNC_DELAY=0ms
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/init:/docker-entrypoint-initdb.d
    networks:
      - adam_network
    # Performance resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    # Optimize for SSD/fast storage
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Grafana - Visualization dashboard
  grafana:
    image: grafana/grafana:12.0.2
    container_name: adam-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      # Increase series limits for industrial data
      - GF_DATAPROXY_MAX_IDLE_CONNECTIONS=1000
      - GF_QUERY_MAX_SERIES=10000
      - GF_ALERTING_MAX_ANNOTATIONS_TO_KEEP=500000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - adam_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Prometheus - Metrics collection and alerting
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: adam-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    networks:
      - adam_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Node Exporter - System metrics
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: adam-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - adam_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

# Persistent volumes for data storage
volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local

# Internal network for service communication
networks:
  adam_network:
    driver: bridge