# Prometheus Configuration for Industrial Counter Data Acquisition Platform
# Comprehensive monitoring setup for counter applications and system metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'adam-counter-monitor'
    environment: 'production'

# Alertmanager configuration (optional - can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load alerting rules
rule_files:
  - "alert-rules.yml"

# Scrape configurations for different targets
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # System metrics from Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-counter-system'

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-influxdb'

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-grafana'

  # ADAM Counter Logger application metrics (when implemented)
  - job_name: 'adam-counter-logger'
    static_configs:
      - targets: ['adam-logger:8080']  # Assuming metrics endpoint on port 8080
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-counter-logger'
    # Custom metric relabeling for industrial applications
    metric_relabel_configs:
      # Relabel device-specific metrics
      - source_labels: [device_id]
        target_label: adam_device
      - source_labels: [channel_number]
        target_label: adam_channel
      # Add industrial-specific labels
      - target_label: application
        replacement: 'industrial-counter'
      - target_label: component
        replacement: 'data-acquisition'

  # Custom application health checks
  - job_name: 'adam-health-checks'
    static_configs:
      - targets: ['adam-logger:8080']
    scrape_interval: 30s
    metrics_path: /health/prometheus
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-health'

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'adam_.*'
#         action: keep