# Prometheus Configuration for Industrial Counter Data Acquisition Platform
# Comprehensive monitoring setup for counter applications and system metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'adam-counter-monitor'
    environment: 'production'

# Alertmanager configuration (optional - can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load alerting rules
rule_files:
  - "alert-rules.yml"

# Scrape configurations for different targets
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # System metrics from Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-counter-system'

  # TimescaleDB metrics - Disabled (PostgreSQL doesn't expose /metrics by default)
  # Note: To monitor TimescaleDB, would need postgres_exporter sidecar container

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'adam-grafana'

  # ADAM Counter Logger - Disabled (application doesn't expose /metrics endpoint)
  # Note: To monitor the logger application, would need to implement custom metrics endpoint

  # Custom health checks - Disabled (application doesn't expose /health/prometheus endpoint)
  # Note: Application health is monitored via Docker health checks

# Remote write configuration (optional - for long-term storage)
# Note: TimescaleDB integration would require a different approach
# Could use postgres_exporter or direct SQL writes for custom metrics